### ISSUE TITLE
次回講義の日程、時間帯に取り扱う内容の確認

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#108]
各何月何日の @knokmki612 と @Hidetaro7 の担当時間にどの範囲を取り扱うのか明確になったら完了

**Comment by knokmki612** [comment]
担当時間の整理

- 6月22日
    - ひでさん: 10:00～12:00
    - くの: 13:00～15:30
    - ひでさん: 15:30～17:00
- 6月29日
    - ひでさん: 10:00～12:00
    - くの: 13:00～15:30
    - ひでさん: 15:30～17:00
- 7月6日
    - ひでさん: 10:00～12:00
    - くの: 13:00～15:30
    - ひでさん: 15:30～17:00
    
15時の交代は厳密に考えずひでさんが戻ってきたタイミングでの交代（実質的に15時はひでさんの休憩時間が終わり次第の交代）

**Comment by knokmki612** [comment]
取り扱う内容はだいたい2時間前後ですすめられる内容で想定

**Comment by knokmki612** [comment]
> 自習時間を除き、全 16 時間を想定しています。
> 
> 1. Vue 3 のハンズオン (8 時間)
> 2. Vue 3 周辺ライブラリのハンズオン (2 時間)
> 3. Vue 3 サンプルアプリケーションのハンズオン (2 時間)
> 4. Nuxt 3 のハンズオン (4 時間)

にそうならば


- 6月22日
    - ~~ひでさん: 10:00～12:00~~
    - くの: 13:00～15:30 Vue 3 のハンズオン
    - ひでさん: 15:30～17:00 Vue 3 のハンズオン
- 6月29日
    - ひでさん: 10:00～12:00 Vue 3 のハンズオン
    - くの: 13:00～15:30 Vue 3 のハンズオン
    - ひでさん: 15:30～17:00 Vue 3 周辺ライブラリのハンズオン
- 7月6日
    - ひでさん: 10:00～12:00 Vue 3 サンプルアプリケーションのハンズオン
    - くの: 13:00～15:30 Nuxt 3 のハンズオン
    - ひでさん: 15:30～17:00 Nuxt 3 のハンズオン

**Comment by knokmki612** [comment]
基本的な構成

- 演習は時間調整に使う（解答も用意してるので厳密に進行せず次週時間的になる）

**Comment by knokmki612** [comment]
- Vue 3 のハンズオン
    - はじめに しゃべるだけ https://tuqulore.github.io/vue-3-practices/3
    - 準備 しゃべるだけ https://tuqulore.github.io/vue-3-practices/4
    - Options API と Composition API の違い しゃべるだけ https://tuqulore.github.io/vue-3-practices/5
    - まずは書いてみる カウンターのハンズオン https://tuqulore.github.io/vue-3-practices/7
    - リアクティブの探求 しゃべるだけ https://tuqulore.github.io/vue-3-practices/8
    - リアクティブの探求 refとcomputedのハンズオン https://tuqulore.github.io/vue-3-practices/10
    - リアクティブの探求 reactiveのハンズオン https://tuqulore.github.io/vue-3-practices/11
    - リアクティブの探求 toRefsのハンズオン https://tuqulore.github.io/vue-3-practices/12
    - リアクティブの探求  reactiveとreadonlyのハンズオン（前回はスキップ） https://tuqulore.github.io/vue-3-practices/13
    - テンプレート構文 テキスト展開のハンズオン https://tuqulore.github.io/vue-3-practices/15
    - テンプレート構文 リアクティブな値のテキスト展開のハンズオン https://tuqulore.github.io/vue-3-practices/16
    - テンプレート構文 ディレクティブのハンズオン 静的な値のv-bind https://tuqulore.github.io/vue-3-practices/17
    - テンプレート構文 ディレクティブのハンズオン クリックのv-on https://tuqulore.github.io/vue-3-practices/18
    - テンプレート構文の10枚
    - 条件付きレンダリング 2ハンズオン 5枚
    - リストレンダリング 1ハンズオン 2枚
    - イベントハンドリング 1ハンズオン 1枚
    - フォーム入力バインディング 1ハンズオン 1枚
    - ライフサイクル スキップ

----

困ること ハンズオンの途中で交代は無理なので、とちゅうでひでさんが戻ってきてもキリがいいところまですすめる

**Comment by knokmki612** [comment]
スライドの内容に記載のない発展的な内容（ハンズオン）は、できれば取り扱う（準備に負担があればやらない）

スライドに書いてあることをそのまま書き写して動いたら次のページへ、を最低限とする

**Comment by knokmki612** [comment]
終わるまで閉じない

**Comment by knokmki612** [comment]
3\. 4\. (最終日まるまる)の構成をごそっと変える必要がありそうという話をした

- サンプルアプリの自由時間は課題設定がなく活用出来なかった
- Nuxt 3の自由時間は課題設定がなく活用出来なかった
- ルーティングまわりが説明不足

---

> 自習時間を除き、全 16 時間を想定しています。
> 
> 1. Vue 3 のハンズオン (8 時間)
> 2. Vue 3 周辺ライブラリのハンズオン (2 時間)
> 3. Vue 3 サンプルアプリケーションのハンズオン (2 時間)
> 4. Nuxt 3 のハンズオン (4 時間)

にそうならば


- 6月22日
    - ~~ひでさん: 10:00～12:00~~
    - くの: 13:00～15:30 Vue 3 のハンズオン はじめに～リアクティブの探求
    - ひでさん: 15:30～17:00 Vue 3 のハンズオン リアクティブの探求～テンプレート構文
- 6月29日
    - ひでさん: 10:00～12:00 テンプレート構文
    - くの: 13:00～15:30 テンプレート構文～コンポーネント
    - ひでさん: 15:30～17:00 コンポーネント～Vue 3 周辺ライブラリのハンズオン
- 7月6日
    - ひでさん: 10:00～12:00 Vue 3 靴ギャラリーのハンズオン
    - くの: 13:00～15:30 Nuxt 3 のハンズオン（未定）
    - ひでさん: 15:30～17:00 Nuxt 3 のハンズオン（未定）

**Comment by Hidetaro7** [comment]
7月6日
1. ひでさん: 10:00～12:00 Vue 3 靴ギャラリーのハンズオン
2. くの: 13:00～15:30 Nuxt 3 のハンズオン（未定）
3. ひでさん: 15:30～17:00 Nuxt 3 のハンズオン（未定）

2.でNuxt3でできることの入門をくのがやる
3.で各受講者のレベルに応じて3つの課題を選んでつくってもらう

**Comment by knokmki612** [comment]
ひととおり日程と内容が確定したので完了
