### ISSUE TITLE
CodeSandboxで準備したハンズオン環境の確認

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#110]
前回使用したハンズオン環境をこのリポジトリに反映なりする目的で、urlなど共有いただけるとありがたいです

書き換える前のプロジェクト、書き換えた後のプロジェクトがそろっているとよりよいです

**Comment by Hidetaro7** [comment]
記録していたメモを一旦そのまま貼り付ける

---

子、孫のコンポーネントがひな形として用意されている
[StackBlitz]
https://stackblitz.com/edit/github-6cbxwo
[CSB]
https://codesandbox.io/s/vue3-tuqulore-temp-0jqn8

【問題】

1. なぜかChildComponentが表示されないので、表示してください 

https://codesandbox.io/s/amazing-star-19zbz

2. ここからChildComponentに「こんにちは」という文字をpropsで送って「こんにちはChildComponent」と表示させてください

https://codesandbox.io/s/icy-grass-tjt7t

3. 子のボタンが押されたときに親がalertを出す仕組みをつくってください

https://codesandbox.io/s/peaceful-tdd-dj1jw



computed 例

<script>
import { ref, computed } from "vue";

export default {
  setup() {
    const price = ref(100);
    const taxRate = ref(10);
    const includeTax = computed(() => {
      return Math.floor(price.value * (1 + taxRate.value / 100));
    });
    return { price, includeTax, taxRate };
  },
};
</script>

<template>
  <div>
    <p>価格: <input type="number" v-model="price" /></p>
    <p>税率: <input type="number" v-model="taxRate" /></p>
    {{ includeTax }}
  </div>
</template>


JSONデータサンプル

[
	{  "name" : "北田 由宇", "email" : "kitada_yuu@example.com", "pref" : "東京都",  "city" : "府中市", },
	{  "name" : "小幡 有起哉", "email" : "obata_yukiya@example.com", "pref" : "大分県",  "city" : "豊後高田市",},
	{  "name" : "伊藤 まひる", "email" : "itou_mahiru@example.com", "pref" : "熊本県",  "city" : "葦北郡芦北町", },
	{  "name" : "有賀 雅功",  "email" : "ariga_masatoshi@example.com", "pref" : "徳島県",  "city" : "鳴門市", },
]


JSON読み込み

<template>
  <ul>
    <li v-for="(user, index) in userData" :key="index">
      <img :src="'/image/' + user.photo_url" alt="" />
      {{ user.name }}
    </li>
  </ul>
</template>

<script>
import { ref } from "vue";
export default {
  setup() {
    const userData = ref([]);
    const loadUserData = async () => {
      const res = await fetch("/json/users.json");
      userData.value = await res.json();
    };
    loadUserData();
    return {
      userData,
    };
  },
};
</script>


検索のようなもの


<script>
import _ from "lodash";
import { ref } from "vue";
export default {
  setup() {
    const message = ref("");
    const originalFruits = [
      "orange",
      "banana",
      "strawberry",
      "grape",
      "watermelon",
    ];
    const fruits = ref(originalFruits);
    const updateText = _.throttle(() => {
      console.log(message.value);
      fruits.value = originalFruits.filter(
        (fruit) => fruit.indexOf(message.value) >= 0
      );
    }, 1000);
    return {
      updateText,
      fruits,
      message,
    };
  },
};
</script>

<template>
  <input type="text" v-model="message" @input="updateText" />
  <ul>
    <li v-for="(fruit, index) in fruits" :key="index">
      {{ fruit }}
    </li>
  </ul>
</template>

<style>
</style>



- setup関数の基礎が理解できた
- ref, reactiveの違いについて理解できた
- computedとmethodsではキャッシュがされる・されないという違いがあることについて理解できた
- コンポーネントに値（props）を与える方法を理解できた
- コンポーネントから親コンポーネントにイベントを発火する方法を理解できた
- コンポーネントでv-modelを使った双方向バインディングの利用方法が理解できた

- Nuxtの開発環境では多くのモジュールのimportを省略できることが理解できた
- NuxtでもVueの講義で学習した基本的な処理は問題なく書いて動かせた
- Suspenseの目的や使い方は一通り理解できたと思う
- server/apiからuserFetchを使ってデータを取得する基本的な流れを理解した


https://codesandbox.io/s/falling-bash-kmt9l?file=/src/App.vue




v-modelはこれの糖衣構文

v-modelを使わない煩雑な書き方
https://codesandbox.io/s/input-twoway-basic-w0bbq
上記をv-modelを使った場合
https://stackblitz.com/edit/github-ffg6rn-jtqhgs?file=src%2FApp.vue&terminal=dev

上記、input要素をVueコンポーネントでもv-modelで実現したい


コンポーネントでv-modelを使う
v-modelを使わない煩雑な書き方
https://codesandbox.io/s/twoway-binding-51cvd
上記をv-modelを使った場合
https://stackblitz.com/edit/github-g4mpay-yzwkr6?file=src%2FApp.vue&terminal=dev


カスタムレイアウトはsetup内に
definePageMeta({
      layout: 'custom',
    });
と書いて、変わらなければ更新ボタンが必要

今日はずっとハンズオン

https://stackblitz.com/github/tuqulore/vue-3-practices/tree/main/nuxt-template?file=app.vue&terminal=dev

**Comment by Hidetaro7** [comment]
共有したのでクローズする
