### ISSUE TITLE
理解度アンケートの項目の検討

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#149]
5段階で理解度をとう項目を検討できたら完了

前回の項目

- 03_Vue.jsがリアクティブであることによって何が嬉しいか
- 03_Vue.jsの単一ファイルコンポーネントの構成
- 03_Vue.jsのテンプレート構文
- 03_Vue.jsのイベントハンドリング、フォーム入力バインディング
- 04_setup関数の基礎が理解できた
- 04_ref, reactiveの違いについて理解できた
- 04_computedとmethodsの違い(キャッシュの有無)を理解できた
- 04_コンポーネントに値（props）を与える方法を理解できた
- 04_コンポーネントから親コンポーネントにイベントを発火する方法を理解できた
- 04_v-modelを使った双方向バインディングの利用方法が理解できた
- 05_小規模のVueアプリのコードを読み理解できる
- 05_Vueアプリにおける画面遷移処理が実装できる
- 05_Nuxtでは多くのモジュールのimportが省略可能と理解した
- 05_NuxtでもVueで書いてきた基本的処理は問題なく書いて動かせる
- 05_Suspenseの目的や使い方は一通り理解できたと思う
- 05_server/apiからuseFetchでデータを取得する基本的な流れを理解した

**Comment by knokmki612** [comment]
> - 03_Vue.jsがリアクティブであることによって何が嬉しいか
> - 03_Vue.jsの単一ファイルコンポーネントの構成
> - 03_Vue.jsのテンプレート構文
> - 03_Vue.jsのイベントハンドリング、フォーム入力バインディング

- 03_リアクティブがどんなものか理解できた
- 03_refによるリアクティブな値の作り方が理解できた
- 03_computedと関数呼び出しの違いを理解できた
- 03_watchでリアクティブな値が監視できることを理解できた

**Comment by knokmki612** [comment]
- 04_前回のテンプレート構文の書き方と機能についてひととおり理解できた
- 04_コンポーネントの親子間のデータの受け渡し方について理解できた

あと4項目必要

**Comment by Hidetaro7** [comment]
> 04_コンポーネントの親子間のデータの受け渡し方について理解できた

04_親コンポーネントから子コンポーネントへpropsによるデータの渡し方が理解できた
04_子コンポーネントのイベントをきっかけに、親コンポーネントへemitする方法を理解できた

と、分けてしまい、

- 04_前回のテンプレート構文の書き方と機能についてひととおり理解できた
- 04_コンポーネントを自作できるようになった
- 04_コンポーネントを別のコンポーネントに呼び出すことができるようになった
- 04_親コンポーネントから子コンポーネントへpropsによるデータの渡し方が理解できた
- 04_子コンポーネントのイベントをきっかけに、親コンポーネントへemitする方法を理解できた
- 04_コンポーネントにslotを使ってHTMLや文字列を渡す方法が理解できた

かなりコンポーネントの項目になってしまったが。

**Comment by knokmki612** [comment]
> コンポーネントの項目になってしまったが

はい、他の内容も取り扱うはずなのでそれを4項目分埋めるのかコンポーネントの理解度項目を増やしてその分減らすのか分からないですが、項目としてはコンポーネント以外も取扱いたいです

**Comment by knokmki612** [comment]
コンポーネントの理解度の項目をもう少しこまかく分解したい気もしますが、他をまとめる方法が思いつかなかったのでこれでいこうかと思いました。ありがとうございます

- 04_前回のテンプレート構文の書き方と機能についてひととおり理解できた
- 04_コンポーネントの親子間のデータの受け渡し方について理解できた
- 04_小規模なVueアプリのコードの読み方、コードの足し方が理解できた
- 04_throttle-debounceでイベント処理が間引けることが理解できた
- 04_Vue Routerが何をやってくれるのか、どうやって使うのか理解できた
- 04_Fetch APIをVueでどうやって使うのか理解できた

**Comment by knokmki612** [comment]
項目案

- 05_Vueコンポーネントの処理の一部をコンポジション関数として分離できること
- 05_Nuxt3ではインポートが省略できること
- 05_Nuxt3ではルートの定義をファイルとディレクトリの配置でおこなえること
- 05_Nuxt3ではAPIサーバーにあたる処理を実装できること
- 05_Nuxt3では共通レイアウトを切り替えられる仕組みがあること
- 05_Nuxt3が提供するuseFetchを使うと何がうれしいのか

**Comment by knokmki612** [comment]
ひととおり確定したので完了
