### ISSUE TITLE
期待通り動かないコードがある

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#161]
リアクティブな値でないので、文字列の並びを変更してもレンダリングに反映されない

https://tuqulore.github.io/vue-3-practices/25

**Comment by Hidetaro7** [comment]
returnが書いてないようですね

**Comment by knokmki612** [comment]
そもそもイベントハンドリングのサンプルコードが多いのでこのサンプル自体取り除くことで対処したいと思う
