### ISSUE TITLE
Componentを使った双方向バインディングのサンプルコード

### ISSUE THREAD

**Issue by Hidetaro7** [tuqulore/vue-3-practices#172]
コピペするのが大変そうで、サンプルがなさそうだったことに気づき、講義をスムーズにするためにStackblitzのサンプルを用意しておいた。
不要であればクローズしてよい、有用であれば、リポジトリに追加する判断をしたい。

スライドの42P目（v-modelを用いた..）
https://stackblitz.com/edit/tuqulore-vue-3-practices-8mmntp?file=src%2FApp.vue,src%2Fcomponents%2FChildComponent.vue&terminal=dev

スライドの43P目（v-modelを用いない...）
https://stackblitz.com/edit/tuqulore-vue-3-practices-qqwr1c?file=src%2FApp.vue,src%2Fcomponents%2FChildComponent.vue&terminal=dev

**Comment by knokmki612** [comment]
スライドの42P目（v-modelを用いた..）
スライドの43P目（v-modelを用いない...）

この2ページの差分って、実質的に親の呼び出し部分の1行が違うだけだったと思うのでどちらかがあればいいような気がします

また、私からはコピペが大変かどうか、サンプルが必要かは判断がつかないです。

子コンポーネントがあることで前回よりコード量が多いということであれば、コンポーネントの説明のサンプルはだいたい大変という話なのかなと思いました。

私の持ち時間ではそもそもコピペでなくて喋りながら書き写しているので、そのあたりすすめかた任せます
書き写すべきかコピペでいいのかについては、何度も講座で頻出している部分はスキップでも
いいのではという話を前回の振り返りでした気がしますが
私としては何度も同じ部分がでてくることを認識してもらうのも慣れてもらうのに意味があるかなとは思っています

**Comment by Hidetaro7** [comment]
指摘の通り一行の変更なだけなのでここまでやらなくてよいので取り下げ
