### ISSUE TITLE
「靴のギャラリーとショッピングカート」ハンズオン画面上部とUAのスタイルシートのmarginが競合しているように見える

### ISSUE THREAD

**Issue by kou029w** [tuqulore/vue-3-practices#180]
![](https://user-images.githubusercontent.com/1730234/176330426-729aad41-3245-4899-8fe6-014e5ca2fc4a.png)
[「靴のギャラリーとショッピングカート」ハンズオン](https://stackblitz.com/github/tuqulore/vue-3-practices/tree/main/handson-gallery-shoes-cart-finish?file=src/App.vue&terminal=dev)にて、プレビュー画面上部のヘッダー部分とUAのスタイルシートのbodyのmarginが競合して隙間が見える。
ここで本来期待する見た目としては上部に張り付いているようなものではないでしょうか? もし仮にそうであれば、そのような見た目に修正するorそのような見た目にするための手段をお伝えするのがより良いのではないかと考えました。
(あるいはもし意図通りの見た目であれば本件は無視してクローズしてください。)

環境:  Chrome 103

**Comment by knokmki612** [comment]
> 意図通りの見た目であれば

意図どおりではないと思います

**Comment by knokmki612** [comment]
対応したつもりですが、もし解決していないようにみえましたらコメントなどいただければと思います :pray:
