### ISSUE TITLE
Nuxt3 午前中のハンズオン教材

### ISSUE THREAD

**Issue by Hidetaro7** [tuqulore/vue-3-practices#187]
Nuxt3のイントロダクションが終わり次第「色々触ってみよう」のための教材。

配布用（こちらだけリポジトリに含めたい）
https://stackblitz.com/edit/tuqulore-vue-3-practices-muomqm?file=app.vue&terminal=dev

完成（こちらはリポジトリにふくめない）
https://stackblitz.com/edit/tuqulore-vue-3-practices-3nq8ch?file=pages%2Findex.vue&terminal=dev

**Comment by knokmki612** [comment]
https://stackblitz.com/fork/github/tuqulore/vue-3-practices/tree/main/handson-nuxt-playground?file=app.vue&terminal=dev を差し替えるという形で対応しようかと思いました

**Comment by knokmki612** [comment]
@Hidetaro7 プルリクにしましたので確認いただければと思います :pray:
