### ISSUE TITLE
Nuxt版デザインラボ記事ビューアーがStackBlitzで動作しない

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#193]
確認方法

https://stackblitz.com/fork/github/tuqulore/vue-3-practices/tree/main/handson-fetch-router-nuxt-finish?file=src/App.vue&terminal=dev にアクセス

期待：記事一覧が表示される
実際：500 post.title is undefined が表示される

useFetchで取得している記事リストのJSONファイルが、なぜか一部分の文字列しか取得できておらずJSONとして認識されていない。

ローカルでは正常に動作する

**Comment by dynamis** [comment]
StackBlitz いつものローカルに対する fetch が正常動作しない問題 (の亜種？) ですね。

https://github.com/stackblitz/core/issues/331

2018 年から外部 URL するか fetch せずコードに埋め込んでくれ、あるいは webpack みたいにビルド時に勝手に埋め込みに切り替えてくれるものを使ってくれというので放置っぽいですからね...

**Comment by knokmki612** [comment]
https://stackblitz.com/edit/tuqulore-vue-3-practices-ckmb2h?file=pages%2Findex.vue&terminal=dev にて raw.githubusercontent.com からjsonファイルを取得するようにしてみましたが、stringのまま得られてしまい期待するオブジェクトが得られない現象は改善しませんでした。
Response.json()を明示的に呼び出すようにする必要があるかと思いました。

しかし、現状 https://tuqulore.github.io/vue-3-practices/64 にあるように各人のローカル環境で動作させるように案内しているのと、StackBlitz環境で動作しないという制約からuseFetchを使用した場合に簡便にデータ取得できるという説明がおこないにくいコードに変更することは望ましくないと考えるので、ドキュメントに留意事項として記載することで対処しようかと思いました。

**Comment by knokmki612** [comment]
このissueそのものは解決していないので閉じず残しておきます

**Comment by knokmki612** [comment]
> 確認方法
> 
> https://stackblitz.com/fork/github/tuqulore/vue-3-practices/tree/main/handson-fetch-router-nuxt-finish?file=src/App.vue&terminal=dev にアクセス
> 
> 期待：記事一覧が表示される
> 実際：500 post.title is undefined が表示される
> 
> useFetchで取得している記事リストのJSONファイルが、なぜか一部分の文字列しか取得できておらずJSONとして認識されていない。
> 
> ローカルでは正常に動作する

本日時点だと動作しているようにみえる

![image](https://github.com/tuqulore/vue-3-practices/assets/9744580/d3b3fa75-9cb4-41f2-93e6-7a5a9e692aee)

https://github.com/stackblitz/core/issues/331 は stale としてクローズされている。

**Comment by knokmki612** [comment]
現状安定して動作しているようなのでクローズします。
