### ISSUE TITLE
次回のNuxtの課題の準備

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#201]
#132 を踏まえた反省

ひでさん

コードの説明に終始した。受講者としてはアプリがどういう仕組みで動いているのかを体系立てて理解できるような課題にしたい

唐突に学んでいない内容がでてくるのは自力での課題達成が難しい（例：$event、$emitを使用している、dataset要素を使っているなど）

くの

今まで学んだ内容を組み合わせて課題をクリアできる内容であってほしい

**Comment by knokmki612** [comment]
受講者のフィードバックとして、composablesに触れてほしいというのがあったので、課題とその前段階のハンズオンでできるとよさそうに思った

**Comment by knokmki612** [comment]
課題とは

https://tuqulore.github.io/vue-3-practices/73 以降の3つの課題

用意の方法

https://stackblitz.com/fork/github/tuqulore/vue-3-practices/tree/main/handson-nuxt-playground?file=app.vue&terminal=dev をフォークして内容を追加する

既存の課題は考慮しないでゼロベースで考える

**Comment by Hidetaro7** [comment]
- composablesは各ページからよびだす共通のロジックとして使える
- https://vueuse.org/ のサンプルを紹介して付箋を動かす
- server API から何かを取得するサンプルにcomposablesを使うとよい
- serverに初期状態の付箋情報が入っているので、呼び出して配置する

少しハンズオンをやって、ハンズオンの中で穴埋め、その後課題に取り組むと理解が進んだ状態になると思う。

**Comment by Hidetaro7** [comment]
サブページに何かロジックを活用したアイデアを考えて、つくってください。
一つ、例を出してあげる

**Comment by knokmki612** [comment]
コンポジション関数を作る動機は再利用したいロジックがあるところになるので、再利用したくなる場面があると納得感がある。

たとえばx, y, zの3次元座標のリアクティブな値が得られるコンポジション関数usePointを作って、Stickyコンポーネントで使う。
直線とか矢印を表現するコンポーネントを作る場合はusePointを2回呼び出す必要があるだろうし、n角形を表現するコンポーネントを作る場合はn回余尾だす必要がある。

---

ルーティング（ページコンポーネントを追加する）の課題を足すのが難しいようであれば、別のアプリで課題を用意するのも手。例えば紙芝居RPGゲーム的なものをルーティングで表現するアプリを用意するとか。2、3回のクリックですむような短いデモまでを用意して、あとは自由課題でゲームを完成してもらう。

デモ案

1. 女の子がお使いでお店にやってきました。 a: 「おばちゃん、牛乳ください！」→2へ b: なにも買わずに帰る→E1へ
2. おばちゃん「何本だい？」「牛乳をn本ください」（nはパスパラメーターになる）→4本未満ならE2、4本以上ならE3へ

E1 牛乳がないのでお母さんが困る
E2 ハッピーエンド
E3 牛乳を買いすぎてお母さんが困る

**Comment by Hidetaro7** [comment]
デモ案、たしかに牛乳の数がcomposablesで格納されているので良いかもしれないですね。
余談ですが、昔 Nuxt2でこんな診断アプリをつくりました。（確かVuexを使っていた気がする）
https://shimobe-shindan.neurona.jp/


まずは付箋のアイデアから、いきなり複雑にするより、ミニマムでコードを眺めて理解するためだけのサンプルを作りました。
https://stackblitz.com/edit/nuxt-starter-e6lndx

server/api から composables で取得し、reactiveな状態に保持しておく。
トップページだけでまずは参照するだけからスタート。

**Comment by Hidetaro7** [comment]
付箋に背景画像を貼ってみよう。
https://stackblitz.com/edit/nuxt-starter-vdulhp

**Comment by knokmki612** [comment]
> 牛乳の数がcomposablesで格納されているので良いかもしれない

自分の想定としてはパスパラメータから参照するので特別リアクティブな値に入れずともuseRoute()から参照可能ですね

> （確かVuexを使っていた気がする）

グローバルな状態管理がしたければNuxtだとuseState使うのが一番手軽かもしれません

https://nuxt.com/docs/getting-started/state-management

**Comment by Hidetaro7** [comment]
サーバとの連携とグローバル状態管理は分けて課題にしないと入門者には複雑すぎる（私的にも難しい印象だった）
NuxtLinkで遷移しても同じ状態であることのデモだけでも色々なことができそうなので、一旦サーバ連携を諦めてcomposablesのデモにしたくなってきた

**Comment by knokmki612** [comment]
それぞれの課題で何をやりたいのか箇条書きにして整理するといいと思います

**Comment by Hidetaro7** [comment]
https://stackblitz.com/edit/nuxt-starter-eqvxvb

作り直した。これをベースに色々な機能を付けていく方針でカリキュラムをつくりたい。

- composables の状態管理ができると各コンポーネントからアクセス、参照ができる
- 別ページに遷移しても前の状態がそのまま残っている

ここから機能の追加
- 付箋の追加は新しいコンポーネントで行う
- 付箋の削除
- 付箋の背景に写真を貼る
など

**Comment by Hidetaro7** [comment]
付箋を削除する解答例

https://stackblitz.com/edit/nuxt-starter-a1jojw

**Comment by Hidetaro7** [comment]
付箋の背景に写真を貼る解答例

https://stackblitz.com/edit/nuxt-starter-7qahec

**Comment by Hidetaro7** [comment]
付箋の追加ボタンを新規コンポーネントから操作

https://stackblitz.com/edit/nuxt-starter-ryc4pc

**Comment by Hidetaro7** [comment]
他に意欲のある方はどういう機能を付けたいかアイデアから考えてみてください、という流れもよいかも。
例えば

- 重ね順をどう変更するか？ -> 配列の順番を変えたらいいですね
- 文字の色、太さ、影など付けたい -> 背景色の機能を参考にCSSを使ったらよいですね
- 動画を貼りたい -> video要素を使えばできそうだけど、dataURL文字列だと現実的ではないのでサーバーロジックから検討しなければならないかもしれないですね
- カメラを起動させて撮影した写真を貼りたい -> 写真を貼るロジックがほぼそのまま使えそうと思ったが[このあたり](https://developer.mozilla.org/ja/docs/Web/API/Media_Capture_and_Streams_API)が妥当な技術かな
- スタンプを貼りたい -> Stickyコンポーネントのような別のコンポーネントを作る必要があるかもしれない

など、アイデアに対してヒントを出してあげるような時間にすると、受講者のみなさんも楽しいのではないかと思う。

**Comment by Hidetaro7** [comment]
1.最初のハンズオン

app.vueは用意されている
cssは用意されている
足りないところを一緒につくっていくような進行で、StyckyBasicを完成させる。

2.次の自由課題

自分で拡張したい機能を考えて自由時間、都度質問対応

**Comment by Hidetaro7** [comment]
- [ ] スライドに反映させる
- [ ] 概念図となる図版の作成

ができたら完了

**Comment by Hidetaro7** [comment]
図版

![Image](https://user-images.githubusercontent.com/281424/213943601-05b8a8b1-1db1-4351-9bd7-09e6462150cb.png)
