### ISSUE TITLE
SFCにおけるscriptとtemplateの並びを統一したい

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#223]
どのような並びでも動作はするが、並びが不統一だと学習者に混乱をもたらす。

どのような並びにするか方針を決めて反映したら完了

**Comment by knokmki612** [comment]
私の意見としては、比較的新しいドキュメント（Composition API、script setupを用いたサンプルコードがあるページなど）は、script、template、styleの順番で記述されている印象がある。

先にロジックを書くようなスタイルが他のUIフレームワーク（React、Svelteなど）では主流で、それに追従しているのではないかと推測している。

**Comment by knokmki612** [comment]
Nuxt 3はtemplateが先、scriptが後な模様

例 https://nuxt.com/docs/guide/directory-structure/components

**Comment by Hidetaro7** [comment]
> Nuxt 3はtemplateが先、scriptが後な模様

2023年9月現在ではtemplateが後になっている。
公式ドキュメントに従う方針でよいだろう。
