### ISSUE TITLE
付箋サンプルの削除ボタン機能で付箋idが重複して処理される

### ISSUE THREAD

**Issue by Hidetaro7** [tuqulore/vue-3-practices#259]
https://stackblitz.com/edit/nuxt-starter-a1jojw

削除ボタンを押して、付箋の追加ボタンを押すと既存の付箋idと同じidが付与されて削除されてほしくない付箋が削除される。

- [x]  id重複を回避して期待通り削除されたら解決

**Comment by Hidetaro7** [comment]
教材用なのでできるだけシンプルにユニークidを生成するにはどうしたらよいだろう...
本来だったらちゃんとUUID発行してね、と触れといて、`Date.now()`で生成するサンプルにしておいた。

それでも削除した対象の付箋以外が見た目削除されてしまうのでなぜかと思っていたら
v-for の :key にid付与を忘れていた。教えていた身でありながら忘れていた。
講義でkeyを忘れるとどうなるか、触れるといいかもしれない。
期待通り動作したのでクローズ。

**Comment by knokmki612** [comment]
idとして使えそうなランダム値としては `Math.floor(Math.random() * Number.MAX_SAFE_INTEGER)` なども考えられます
