### ISSUE TITLE
共通レイアウトの切り替えの案内が正しくない

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#262]
NuxtLayoutコンポーネントを使用しているがこれは誤り

https://github.com/tuqulore/vue-3-practices/blob/4d6e8ab4c38f23a3273fa0e3dd20857123077276/docs/slides.md?plain=1#L1769-L1783

definePageMetaマクロを使用して切り替えるように書き換えたら完了

https://nuxt.com/docs/guide/directory-structure/layouts#setting-another-layout

**Comment by Hidetaro7** [comment]
1ページで書ききれなかったので、全て共通レイアウトの場合と、レイアウトを分けたい場合のシーンを想定して2ページに分割した。

内容だけでは伝わりにくいので、あらためてStackblitzにてサンプルを作成した。
https://stackblitz.com/edit/tuqulore-vue-3-practices-7glcep?file=pages%2Findex.vue

**Comment by knokmki612** [comment]
> 内容だけでは伝わりにくいので、あらためてStackblitzにてサンプルを作成した。
> https://stackblitz.com/edit/tuqulore-vue-3-practices-7glcep?file=pages%2Findex.vue

Nuxtの一連のページはハンズオンする流れなので、ここだけサンプルをみるというより、ハンズオンする過程でレイアウトを増やす流れにすればいいようにみえます
