### ISSUE TITLE
スライドに記載している動画のリンク切れが生じている

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#269]
Vueのドキュメントサイトが移行されたことに起因するもの
何らかの方法で動画が示していた内容を用意できたら完了

**Comment by Hidetaro7** [comment]
動画や画像ではなく、公式サイトのデモを操作して説明したらよいということになった
https://ja.vuejs.org/guide/extras/reactivity-in-depth.html#what-is-reactivity
