### ISSUE TITLE
教材で目標とするところを最初に示す

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#351]
とくに説明なく、Vueの書き方の説明からはじまるので、「最終目標がなにで、今どの地点なのか分からない」というフィードバックをもらった。

最後の方に「何をこれまでやってきたか、できるようになったか」の説明はあるので、それに対応する「これから全体として何を学んでいくのか、できるようになるのか」の説明があるといいということだと思う

https://github.com/tuqulore/vue-3-practices/blob/27a0b61e53767e43e624671a4c966871eb53a9a1/docs/slides.md?plain=1#L2131-L2148

**Comment by Hidetaro7** [comment]
最終的にどんなものができるのかイメージできることでやる気も変わってくると思うのでそのあたりを最初に見せたらいいのでは？

最終的につくるポケモンのアプリの完成イメージなども動くものを用意しておくでもいい、
またVue/Nuxtの間でも実習があるので、その完成形など冒頭に触ってみるとか。

**Comment by knokmki612** [comment]
> 最終的につくるポケモンのアプリの完成イメージなども動くものを用意しておくでもいい、
> またVue/Nuxtの間でも実習があるので、その完成形など冒頭に触ってみるとか。

そういうものがあってもいいかもしれませんね

**Comment by knokmki612** [comment]
https://tuqulore.github.io/vue-3-practices/45

前半は大体以下が分かる

- Vueとは？
- リアクティブな値の作り方
- テンプレートの書き方
- コンポーネントの作り方

**Comment by knokmki612** [comment]
> 「最終目標がなにで、今どの地点なのか分からない」というフィードバックをもらった。

教材としては「Vueアプリを読める、書き換えられる」あたり。
本当の目標は「Vueアプリが作れる」くらい。
