### ISSUE TITLE
名前付きスロットを取り扱うかどうか

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#354]
使用するケースはなくはないが、初学者が学んでうれしいか検討しておきたい

公式ドキュメント https://ja.vuejs.org/guide/components/slots#named-slots

**Comment by Hidetaro7** [comment]
- ドキュメントを見てもらう
- 最初から名前付きスロットのみ紹介し、もっと簡単な方法もあることを補足する

**Comment by knokmki612** [comment]
> ドキュメントを見てもらう

:+1: https://ja.vuejs.org/guide/components/slots#named-slots をのせておけばOK
