### ISSUE TITLE
スコープ付きスロットを取り扱うかどうか

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#355]
使用するケースはなくはないが、初学者が学んでうれしいか検討しておきたい

公式ドキュメント https://ja.vuejs.org/guide/components/slots#scoped-slots

**Comment by knokmki612** [comment]
https://ja.vuejs.org/guide/components/slots#scoped-slots のリンクをのせて、必要に応じて公式ドキュメントをサラッとみながらなぞれればOK

**Comment by Hidetaro7** [comment]
スコープ付きスロットの解説をする際の[サンプルを考えてみた](https://play.vuejs.org/#eNqtVm1v01YU/it35kOZ1CQlHV+yEKkgpG1iG9r4Nk8i2LfppY5t2TclURWptiG0NGiDqhpMe6tWldJq6ST6oZ2m7sdc8tJ/sXOuX+K4FPiAVFX2uc855znPPec4y8qcbeeXGlQpKWVO67ZR5bSimoSUdbYkH+Bx4VKlv9npb3gi2BP+sQhWywWwqWZ0bldeH62Pdp8Jr1cc7vZOt36Dp9HW7nD7H+E/Haw/EN6fwtsR3n3hrwv/lQjg71cR/CuCx/J5VXgHwnspvC3hrwnfJ7dvOpbe0PgN5vLbRHi76Ot1Ihb+09dHK6OdF8J7jgG934XvQcZzIkvYil8u2BVgGtM6Fv5/wt8Wwb7wuv0HkOCHU29TpjlBB68rvA0ZNI3sDboP+72fgYHtWLYLwQdHWxLek4mgij2IJFY817A4mD679eUN1ABRP401wII2hP8Yc2+DHzzsDdeO+yeHCd84PVTQEd7+OcXt9w+ALkaOEsa4jvwPycLcwBDCQdYXwG20AyS7/b9+PCfoZNEQoXsg/Ef9VeDxRLIPQ4FCIXUpWKhw0hMLxUrSLaHm0DPF8XnDiLoLnlOXTUoM2tC9oiogMBpdVUmAAI17lFzQ6Xy1YXBALhP0IW1VISkogA028Q4WlzuWWasshy55s1qnpN0uFyI7yZH4SKeu5jCbM8sEBLkY222HaejT73Q+nkhWmMhWLkxMU2hK1RmPVkHqkNLM/xtlCwIRrL1Btg8p1qRWMO5EM6ouRqs5TM8hLANCirNnxQNbBmUnoEkZww7JQLOXklI4uZisY7kwXk/vKbdcapHbBBxeQ47EpbyBeVjdthxO0krPO1adTOXTMXFtTn2qmpplAiC+AXKFfIepoBi9RC5NE5SpRKbC1TU3NU1SkoB9ePjH4Pkhrj2c4vtjmJQBIszMzJD29DhkMRPy6pmQp/vPwD56BUO+N8ZE8YrZeLOZeNfOxMMtgXP8ZPDol+HJNuwHxMT8LmM81fweVQ29Ik15y0B580k3kWXMesdydOqAo90krmUwnVzQNA10JMSu6joza1i03ZSWetWpMeBwOXrXmQvX1ioRZhrMpLk7hqUtypN7TOcLsrwIymmT56oGq4G7Rk1OHTADUewpZKZMK9yFu5tntfxd1zLhCyj5qYpm1W1mUOdrKQDMVClkjmdVw7DufSFt3GlQqaP0WaDa4hvsd90m2lTlpkNd6ixRVUnOOBRHeXh8/duvgG/qsA7tZAD6LYffUNCvgRxD2NWGqQPtFE6y/Vx2M+h6y73e5NR046KQKCLDblAV6Odrbyl9THc2/4n0Az1BxcxIgI4gcmYcy/h1Iku5ecuB/SKbgZly3CFHuMYiO74u0lb0lmd6ageVP8rliAgeimBT+C/x2yS/VuGeJLncGIhjfmZPpX7RFJDPuxdBarhtnGxYo9B1ULDtXpS6yAoSjXjLhomYc5xqK9YHvhGpwVDa/wOj+OIE)。

**Comment by Hidetaro7** [comment]
```
<ProductList :items="products">
        <template #default="{ item }" >
```

templateは不要で、ProductList の属性にv-slotでitemを渡すような書き方が好ましい。
修正する。
