### ISSUE TITLE
コンポーネントが何なのかの説明

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#367]
以前は用語集に書いてあったが、スライドには記載がない。どこかしらにあると受講者にとってうれしい。

**Comment by knokmki612** [comment]
https://tuqulore.github.io/vue-3-practices/35

- 見た目やロジックが再利用できる

など

**Comment by Hidetaro7** [comment]
図版

![image](https://github.com/user-attachments/assets/252f1839-cc13-4c70-9f7b-803da7b19668)

https://www.figma.com/design/0jTDbWHHRrWt0w20Sb8sZs/vue-3-practices?node-id=1-2&node-type=frame&t=pS96I4bqbCQxPPeF-11

**Comment by Hidetaro7** [comment]
このような見た目やロジックが決まっている要素は「コンポーネント」に分離して管理することができます。
コンポーネントは内包するデータや状態の変化に柔軟に対応できるような設計、いわゆる「再利用性」が求められます。

これを見ると、`<ChatItem />`コンポーネントに内包する個別のデータを渡しています。この渡しているデータのことを`props`と呼んでいます。このように様々なチャットの会話内容を一つのコンポーネントで取り扱うことができます。

渡すpropsの条件によって、コンポーネント内部で見た目を分けることもできます。この例の場合だと自分と他者の発言によって右寄せ、左寄せにレイアウトして色も変える、ということも可能です。

**Comment by Hidetaro7** [comment]
図版改訂
![image](https://github.com/user-attachments/assets/c82f9f78-99b5-430c-ac82-a6bbe764dd4d)
