### ISSUE TITLE
一部の教材ディレクトリにおいて npm install が期待通り行われない

### ISSUE THREAD

**Issue by Hidetaro7** [tuqulore/vue-3-practices#379]
研修中に説明された通りに操作したにも関わらず環境インストールができない。
例えば `handson-nuxt` ディレクトリなどで起こる。

現象（説明した通りの操作から始める）

1. VSCodeエクスプローラーより右クリック「統合ターミナルで開く」
2. 指定したディレクトリ配下でのターミナルが開く
3. 念のため `pwd` すると `xxxx/vue-3-practices-main/handson-nuxt` と出て問題ないように見える
4. `npm install` すると、親ディレクトリに node_modules が生成され
```
up to date, audited 846 packages in 2s

152 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

などと表示される

nodeバージョンは 18 or 20
package.json は問題なく存在しているが同じディレクトリにはnode_modulesが生成されない
ちなみに、handson-gallery-shoes ディレクトリでは期待通りインストールできた

**Comment by knokmki612** [comment]
> package.json は問題なく存在しているが同じディレクトリにはnode_modulesが生成されない

handson-sticky/node_modules ディレクトリがなくとも、npmはworkspace機能に対応しているため、実際には必要なnpmパッケージがインストール済みかもしれません

参考 https://docs.npmjs.com/cli/v10/using-npm/workspaces

そのまま `npm run dev` を実行して動作するか確認いただきたいです。

ちなみに私の場合はcomposablesのAuto Importに失敗するケースがあるみたいなのですが、zipの展開からやりなおしたところ解消しました。原因は不明です。

**Comment by Hidetaro7** [comment]
> そのまま `npm run dev` を実行して動作するか確認いただきたいです。

```
hidekiakiba@Hideki-no-MacBook-Pro-3 handson-nuxt % np
m run dev

> vue-3-practices-handson-nuxt@1.0.0 dev
> nuxt dev

sh: nuxt: command not found
npm ERR! Lifecycle script `dev` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: vue-3-practices-handson-nuxt@1.0.0 
npm ERR!   at location: /Users/hidekiakiba/Desktop/vue-3-practices-main/handson-nuxt 
```

確かに該当のディレクトリ内で実行しているはずですがこのようなエラーが出ます。

**Comment by knokmki612** [comment]
> sh: nuxt: command not found

この表示自体はnuxtコマンドが存在しないことで表示されているようです。しかし、npm installが正常に実施されているなら生じないはずです。
今のところ原因が分からないです。

`npm -v` や `node -v` でお使いのバージョンを教えていただけますでしょうか。私の場合は以下のバージョンで動作確認しているようです

```console
$ npm -v
10.1.0
$ node -v
v20.9.0

**Comment by Hidetaro7** [comment]
```
% npm -v
10.2.3

% node -v
v18.19.0
```

バージョンはさほど変わらず、原因とは考えられない。

```
(0 , _nuxt.defineNuxtConfig) is not a function
```

eslint の設定によるエラーの可能性が高いことがペアワーク中にわかった。

**Comment by Hidetaro7** [comment]
また公式ではnuxt.configでは `defineNuxtConfig` のimportは記載されていない、auto import されると思われる。

**Comment by knokmki612** [comment]
> また公式ではnuxt.configでは defineNuxtConfig のimportは記載されていない、

https://nuxt.com/docs/getting-started/configuration には記載ないですが、 https://nuxt.com/docs/guide/directory-structure/nuxt-config には記載があります

> You can explicitly import defineNuxtConfig from nuxt/config if you prefer:

**Comment by knokmki612** [comment]
> > そのまま `npm run dev` を実行して動作するか確認いただきたいです。
> 
> ```
> % npm run dev
> 
> > vue-3-practices-handson-nuxt@1.0.0 dev
> > nuxt dev
> 
> sh: nuxt: command not found
> npm ERR! Lifecycle script `dev` failed with error: 
> npm ERR! Error: command failed 
> npm ERR!   in workspace: vue-3-practices-handson-nuxt@1.0.0 
> npm ERR!   at location: /Users/hidekiakiba/Desktop/vue-3-practices-main/handson-nuxt 
> ```
> 
> 確かに該当のディレクトリ内で実行しているはずですがこのようなエラーが出ます。

これについてはZIPをダウンロードするところから再試行してもらったところ、再現しなかった。


また何かあれば再オープンや起票などをお願いします。この場ではひとまずhandson-nuxtやhandson-stickyが `npm run dev` で起動することまで確認したので、クローズします。
