### ISSUE TITLE
CodeSandboxで演習が文字化けする

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#38]
再現手順

- https://codesandbox.io/s/github/tuqulore/vue-3-practices/tree/main/practice-style?file=/src/App.vue にアクセスする

**Comment by kou029w** [comment]
文字化けが再現することを私の方でも確認しました。
また、フォークしても同様の問題が再現します。
一方、フォークした後、編集など行えるように CodeSandbox の自身のサンドボックスのDraftsとしてフォークしなおすと、再現しなくなることがあることはありました。
しかし、HMR の機能しない件も含めいくつか正常に機能しないことを考えると、基本的に CodeSandbox 以外で進めてもらうのが良さそうですね。

---

> * https://codesandbox.io/s/github/tuqulore/vue-3-practices/tree/main/practice-style?file=/src/App.vue にアクセスする

アクセスしコンテナの起動完了後、 https://cb1j1.sse.codesandbox.io/src/App.vue にアクセスするとこのファイルの受信で文字化けを確認。

```console
$ curl -i https://cb1j1.sse.codesandbox.io/src/App.vue
HTTP/2 200 
date: Fri, 21 Jan 2022 00:57:02 GMT
content-type: application/javascript
cf-ray: 6d0c960d98ed0af4-NRT
access-control-allow-origin: *
cache-control: no-cache
etag: W/"5ef-eeamnCpvjNl/m1zCtOQCG7GP/l8"
strict-transport-security: max-age=15724800; includeSubDomains
vary: Accept-Encoding
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

ペイロードに含まれる文字列は下記のように文字化け。

```
const _hoisted_1 = /*#__PURE__*/_createElementVNode("h1", null, "è¦åºã", -1 /* HOISTED */)
```

`è¦åºã` これは `見出し` の UTF-8 のバイト列を、latin-1 (ISO-8859-1) として解釈し、結果得られた文字列を再びUTF-8に変換して得られるバイト列。
ここでは `content-type: application/javascript` となっており、ES5以降を解釈する現代のWebブラウザーはデフォルトでUTF-8として解釈するためサーバーとクライアント間での齟齬は無い。

考察

気になるポイントとしては、content-type ヘッダーに charset が含まれないのでWebブラウザー以外のクライアントで解釈の曖昧さは生まれうる。ちなみに / に関しても `text/html` ではあるが同様に charset は含まれていない様子。
`server: cloudflare` となっており、おそらく Cloudflare が中継している。
charset ヘッダーを含めないことによって CodeSandbox のサーバーと中継している Cloudflare のサーバー間で何かしら齟齬があったのではないか。

**Comment by knokmki612** [comment]
詳細な調査ありがとうございます :pray:

> しかし、HMR の機能しない件も含めいくつか正常に機能しないことを考えると、基本的に CodeSandbox 以外で進めてもらうのが良さそうですね。

このissueは根本的解決がされるまで残しておき、直近はStackBlitzをデフォルトとしたドキュメンテーションに変更することによって対処しようかと思います。

**Comment by knokmki612** [comment]
https://github.com/tuqulore/vue-3-practices/issues/128 でサポートからドロップしたので完了
