### ISSUE TITLE
付箋アプリの図版の更新

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#390]
https://github.com/tuqulore/vue-3-practices/pull/381 にてコンポーネント名を変更したので図版の更新が必要

![](https://raw.githubusercontent.com/tuqulore/vue-3-practices/e6e6869d1372eabce1554c32731f3cd08cd66336/docs/public/sticky-handson.png)
https://github.com/tuqulore/vue-3-practices/blob/e6e6869d1372eabce1554c32731f3cd08cd66336/docs/public/sticky-handson.png

**Comment by Hidetaro7** [comment]
![Image](https://github.com/user-attachments/assets/db49f6bd-43ff-4f81-a7c1-ea9374ce43ea)

https://www.figma.com/design/0jTDbWHHRrWt0w20Sb8sZs/vue-3-practices?node-id=1-45&node-type=frame&t=pS96I4bqbCQxPPeF-11

まだやらないになっていたが、やるべきと思ったので。
