### ISSUE TITLE
Vue 3.4 に合わせた説明の更新

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#407]
参考 https://blog.vuejs.org/posts/vue-3-4

色々重要な変更があるので説明を更新したほうがいいかも

たとえば

- リアクティビティの変更検知の振る舞いが変わった
- defineModel マクロが追加された（利用が推奨される）
- [ ] #646

**Comment by Hidetaro7** [comment]
https://blog.vuejs.org/posts/vue-3-4#v-bind-same-name-shorthand

なるほど、省略できるんですね。

**Comment by Hidetaro7** [comment]
defineModelの説明に該当するページが2ページに及んでいる

- v-model を用いた親子間コンポーネントのデータの受け渡し
- v-model を用いない親子間コンポーネントのデータの受け渡し

内部がどう処理されているのかを知る場面は初学者にとっては難しい気がしている。
input 要素を使うときも v-model を用いない方法もあるので、コンポーネントのセクションで説明するのはちょっと違う気がするので、defineModel を使用した解説にまとめたい。

**Comment by knokmki612** [comment]
> input 要素を使うときも v-model を用いない方法もあるので、コンポーネントのセクションで説明するのはちょっと違う気がするので、defineModel を使用した解説にまとめたい。

なぜかというとフォーム入力バインディングはネイティブイベントにあわせてv-modelが使える (ようにVueがeasyに処理を書く手段を用意している) のであって、コンポーネントのカスタムイベントの双方向バインディングとは書き味は同じでもやってることがちょっと違うためです。
コンポーネントでのカスタムイベントはイベント発火も自分で書くことになり、双方向バインディングについてVueの世界の話に閉じて説明できます。

**Comment by knokmki612** [comment]
> 内部がどう処理されているのかを知る場面は初学者にとっては難しい

- ハンズオンとして取り組むかは要調整（もしかしたらプロパティ、イベント、双方向バインディングの関係図があればいいのかも）
- 前回説明しづらかった箇所は研修の録画で確認すると発見があるかも

**Comment by Hidetaro7** [comment]
```vue
<input @input="memo = $event.target.value" :value="memo" />
```

みたいなことを説明しようとして説明する私が躓いた経験がある。

**Comment by knokmki612** [comment]
去年のDay4の説明を見返してますが、1時間30分あたりのv-modelの説明までは特に問題なさそうですね。（その後も確認中）

**Comment by knokmki612** [comment]
> 説明する私が躓いた

1時間45分あたりで説明しているけど、放送事故みたいなことにはなっていないみたい。ただ「v-model を用いない」という後戻りみたいな内容を入れないほうが説明しやすいとは思った。
