### ISSUE TITLE
スライドに「Vue.js の開発をはじめるのに便利リンク集」を追加

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#44]
関連 #26 

@kou029w さんのフィードバック

> 受講者としては https://v3.ja.vuejs.org/style-guide/ スタイルガイドの紹介など「Vue.js の開発をはじめるのに便利リンク集」的なものがあると嬉しいのかも。

タイミングとしてはDay5でNuxtアプリを作ってもらうあたり？

[参考資料](https://github.com/tuqulore/vue-3-practices/wiki/%E5%8F%82%E8%80%83%E8%B3%87%E6%96%99)も公式ドキュメントの要約とリンクがあるので紹介していいかも

**Comment by knokmki612** [comment]
@Hidetaro7 こちらスライドに追加できそうでしょうか

**Comment by knokmki612** [comment]
- [ ] スライドに追加する
- [ ] 学習資料のその他に追加する

**Comment by Hidetaro7** [comment]
> スライドに追加する

ひできがやる

**Comment by Hidetaro7** [comment]
PR: https://github.com/tuqulore/vue-3-practices/pull/105
