### ISSUE TITLE
useState() の効用（なにがうれしいか＆Composition APIよりなにがいいか）の説明

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#617]
付箋アプリで使っているが、Nuxtの説明としてあると親切

**Comment by Hidetaro7** [comment]
状態管理に関してこだわりがないらしいので、useState が必ずとも必要と考えるのではなく、ニーズに合わせて選定することも大切とのこと。
https://nuxt.com/docs/getting-started/state-management#using-third-party-libraries

**Comment by Hidetaro7** [comment]
一意のキーを使用してすべてのコンポーネント間で共有される状態管理のコンポーザブル関数であり、コンポーネント同士でpropsやemitによるデータのバケツリレーをせずともグローバルに直接データを扱える。

コンポーザブルとは状態を持つロジックをカプセル化して再利用することができることを指し、
再利用はどこのコンポーネント（Vueファイル）からでもアクセスが可能になる。

Composition APIが提供されるようになって、リアクティブな値をコンポーネントから切り離して管理するComposable Function が使えるようになった。これはjsもしくはtsファイルとしてcomposablesディレクトリ配下に格納することが一般的である。
利点は、どこからでも簡単にアクセスがゆえ自由にデータの変更ができるようになってしまうため、readonlyメソッドでデータ自体は保護したり、ミューテーションできる関数を提供するなどの機能を提供でき、それをコンポーネントから利用することができることで、安全かつ効率的に管理された状態を扱えることにある。

**Comment by Hidetaro7** [comment]
という説明に触れたうえで、counterのサンプルコードでも見せたほうがよさそう。
ただ、Nuxt環境でuseStateを使うので、 Vue Playgroundではないほうでデモを見せるなどで理解を深めてもらいたい。

**Comment by Hidetaro7** [comment]
最低限と思えるコードを書いてみた。
https://stackblitz.com/edit/nuxt-starter-rnflks?file=composables%2Fcounter.js

- 各コンポーネント内部から参照、操作が可能
- データ自体はreadonlyで上書き不可にして、inc, dec 関数で操作する
- composablesディレクトリの簡単な使い方を理解する
- 何かグローバルな情報を扱うサンプルにチャレンジできそう（靴のギャラリーの応用など余裕があれば）

**Comment by Hidetaro7** [comment]
そもそも nuxtの説明で composables について触れているので、ここで説明を増やすで良い気がする
https://github.com/tuqulore/vue-3-practices/blob/4db6309dab91ec6eee358f365adca35a54410fae/docs/slides.md#L1819-L1820

**Comment by Hidetaro7** [comment]
### ref()でいいんじゃないの？

コンポネント外のグローバルな領域でrefを使うと、グローバルな状態として扱えなく、個別のデータとしてしか扱えないことを確認した。

`const count = ref(3);` の場合

![Image](https://github.com/user-attachments/assets/52e37a5f-1146-4b0a-860a-73354896a9c0)

`const count = useState("counter", () => 3);` の場合 
![Image](https://github.com/user-attachments/assets/745b915c-e4c8-46bf-8702-f668ea05e2a5)

**Comment by knokmki612** [comment]
付箋アプリとしては: グローバルな状態管理に使っている

**Comment by Hidetaro7** [comment]
現状スライドの「構成を理解しよう」https://tuqulore.github.io/vue-3-practices/78 の直後に挟んで解説する流れ。

**Comment by knokmki612** [comment]
nuxt ハンズオンで一度触れて、https://tuqulore.github.io/vue-3-practices/78 に一言足す方針にしてみる（最終課題は応用だと思うと新規の内容はその前に触れた方がいいかなと思ったため）
