### ISSUE TITLE
Slidevのローカルの起動に失敗する（node14指定のため）

### ISSUE THREAD

**Issue by Hidetaro7** [tuqulore/vue-3-practices#621]

**Comment by knokmki612** [comment]
> node14指定のため

本リポジトリにあるようであればそのコードの箇所を教えてもらいたいです。

以下では v18 or v20 のようです。

https://github.com/tuqulore/vue-3-practices/blob/253ee7739f0c48dbfec463aa011b3268a903cd4f/package.json#L10

**Comment by Hidetaro7** [comment]
こちらですが、関係なかったようです。

https://github.com/tuqulore/vue-3-practices/blob/253ee7739f0c48dbfec463aa011b3268a903cd4f/docs/netlify.toml#L2

**Comment by Hidetaro7** [comment]
ひとまずエラーログを共有しようと思いましたが
ローカルのパスをここで共有するのもちょっと気が引けるので 社内Slackの自分メモに貼ります。

**Comment by knokmki612** [comment]
以下をお試しください

- お使いのnodeがv20であることを確認
- node_modulesを削除
- `yarn` を実行

**Comment by Hidetaro7** [comment]
成功しました。 readme に記載しておくと良いと思いました。

**Comment by Hidetaro7** [comment]
リポジトリ全体としてはyarnを使用している
