### ISSUE TITLE
style バインディングの存在意義や恩恵がこのサンプルだとよくわからない

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#631]
style バインディングの存在意義や恩恵がこのサンプルだとよくわからない。せめて一部分はtemplateに直接値を書くのではなく、scriptで値を用意して渡すくらいのことをしないと活用のイメージが沸かないという指摘があった。

```vue
<script setup>
const style = { color: "red" };
</script>

<template>
  <span :style="style">...</span>
</template>
```

_Originally posted by @knokmki612 in https://github.com/tuqulore/vue-3-practices/pull/619#discussion_r1815992590_

**Comment by Hidetaro7** [comment]
`<script>` -> `<script setup>`
