### ISSUE TITLE
くのの知人からのフィードバック

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#642]
フィードバックをメモ書きしたものをそのまままずは起票します

- [x] フレームワークは「書き方の決め事集」（定義がおかしいのでは） https://tuqulore.github.io/vue-3-practices/3 https://github.com/tuqulore/vue-3-practices/pull/660
- [x] options api vs composition api の関心ごとの集約とは何か言語化する https://tuqulore.github.io/vue-3-practices/7 https://github.com/tuqulore/vue-3-practices/pull/661
- [ ] #668
    - ダークモードを考慮していない箇所がいくつかあるみたい
- [x] 「利用する」が何かわからない https://tuqulore.github.io/vue-3-practices/13 https://github.com/tuqulore/vue-3-practices/pull/662
- [x] getterだけならgetter setterにしなくていいという一言を加える https://tuqulore.github.io/vue-3-practices/14 https://github.com/tuqulore/vue-3-practices/pull/662
- [x] 役立てる→役立てられる https://tuqulore.github.io/vue-3-practices/15 https://github.com/tuqulore/vue-3-practices/pull/662
- [x] ~~ウォッチャって重要？（手厚く取り上げる必要ないのでは） https://tuqulore.github.io/vue-3-practices/16~~ とりあえず取り扱う
- [x] #657
    - 毎回のセクションの終わりに演習時間が必要
    - 読み手が自律してコードをかけるようになるために、サンプルを2-3個用意して、どこを変えていいのか、変えちゃだめか分かるようにする

**Comment by knokmki612** [comment]
> 演習が必要

案:

- GitHub にある演習用ソースコードに StackBlitz 経由でアクセスして演習できるようにしているが、活用できていない
- GitHub にある演習用ソースコードを廃止して、Vue SFC Playground で演習できるようにする
- スライドに演習ページを追加する

**Comment by Hidetaro7** [comment]
> 毎回のセクション

一日の終わりくらいの粒度という意図もあった？
ただ、テンプレート構文のページの前で一度理解度を試すために、演習を挟んでよいと思う。

「展開」（Mustache）はリアクティブのセクションの前倒しする「まずは書いてみましょう: 現9P」あたり。

**Comment by Hidetaro7** [comment]
> リアクティビティの演習が必要

Vue SFC Play ground にて、 ref, computed の自己チェック用のサンプルファイルをつくる。
- 答え合わせはいらない
- 自由にコーディングしてもらい、あくまで理解度チェックのためにある

**Comment by knokmki612** [comment]
> Vue SFC Play ground にて、 ref, computed の自己チェック用のサンプルファイルをつくる。

既存だとcomputedだとこれが使えそうです
https://stackblitz.com/fork/github/tuqulore/vue-3-practices/tree/main/practice-computed?file=src/App.vue&terminal=dev

**Comment by knokmki612** [comment]
残りは各issueで進めさせてください
