### ISSUE TITLE
リアクティビティの演習が必要

### ISSUE THREAD

**Issue by Hidetaro7** [tuqulore/vue-3-practices#657]
- 毎回のセクションの終わりに演習時間が必要
- 読み手が自律してコードをかけるようになるために、サンプルを2-3個用意して、どこを変えていいのか、変えちゃだめか分かるようにする

> リアクティビティの演習が必要

Vue SFC Play ground にて、 ref, computed の自己チェック用のサンプルファイルをつくる。
- 答え合わせはいらない
- 自由にコーディングしてもらい、あくまで理解度チェックのためにある

P19に理解度チェックタイムのようなページにして、Vue SFC Play groundのURLを貼る。

受講者のスキルによってやれることが変わる可能性を見越し、自由度の高いサンプルとあえて問題形式のサンプルも両方用意しておくとよい、という話になった。

_Originally posted by @Hidetaro7 in https://github.com/tuqulore/vue-3-practices/issues/642#issuecomment-2522164184_

> Vue SFC Play ground にて、 ref, computed の自己チェック用のサンプルファイルをつくる。

既存だとcomputedだとこれが使えそうです
https://stackblitz.com/fork/github/tuqulore/vue-3-practices/tree/main/practice-computed?file=src/App.vue&terminal=dev

_Originally posted by @knokmki612 in https://github.com/tuqulore/vue-3-practices/issues/642#issuecomment-2522166719_

**Comment by Hidetaro7** [comment]
> 既存だとcomputedだとこれが使えそうです
> https://stackblitz.com/fork/github/tuqulore/vue-3-practices/tree/main/practice-computed?file=src/App.vue&terminal=dev

15の倍数は3の倍数でもあり5の倍数でもあるので、その処理を考えるところでプログラム初心者には少しハードル高そうですね。FizzBuzzと表示させるには工夫が必要かも。
Playgroundに移しておきました。その他パターンを出します。

- [プレーンな状態](https://play.vuejs.org/#eNp9kUFLwzAUx7/KM5cqzBXR0+gGKgP1oKKCl1xG99ZlpklIXuag9Lv7krK5w9it7//7v/SXthP3zo23EcVEVKH2yhEEpOhm0qjWWU/QgccV9LDytoWCq4U00tTWBII2NDBN/LJ4Qq0tfFuvlxfFlTRVORzHB/FA2Dq9IOQJoFrfzLouL/d9VfKUU2VcJNhet3aJeioFcymgZFiVR/tiJCjw61eqGW+CNWzepX0pats6pdG/OVKsJ8UEMklswXa/LzkjH3G0z+s11j8n8k3YpUyKd48B/RalODBa+AZpwPPPV9zx8wGyfdTcPgM/MFgdk+NQe4hmydpHvWz7nL+/Ms1XmO8ITdhfKommZp/7UvA/eTxz9X/d2/Fd3pOmF/0fEx+nNQ==)
- [税込み計算機](https://play.vuejs.org/#eNp9Us9rE0EU/lceA1KVmKToKWwDKj3oQUU9ziVuXuLW3dlhZjZGlj2MSBsPWn8gehC0l1LopfTQQxvaP2ZIm576L/TNLmkDLYU5zHzf99773sfk7KGU9UGGrMUCHapIGtBoMtnmIkpkqgzkoLBXC9NEZga7UEBPpQksUM0CF2EqtAGpohBhyQtvLzabd2a46QwJbdYXuQgaVXfqSw+DiYw7BukFEMj2ZGd9ujVqQRAJmgLmg8QlzkSWvEHFGQzuJWkXY4LKSYQ02jBZXQ0a3mfZ4XhvNN09ONn62oI893PvAjkpCrg1JyJ6ejiefBvRsNO176cbX1pwNh45+7M825UNgv396K+zf5z9d7XIffwxWdt39rezm86uO/vf2V/Ofjobf66GBY25BVmNGU159KJ+fUWngpLOvR/OfKZRjOq5NBHlxRl594znOnGcvn9aYkZlWJvh4VsM312Dr+ihxzh7oVCjGlBIF5zpqD6ail5+9QyHdL8gKdksJvUN5EvUaZx5j5XsUSa6ZHtOV7p9Uv6XSPRf6+WhQaFnS3mjXlmUes7o6zy+YfVLu/frD8o6LgpWnAM5Bwi/)
- [結果に応じて文字を表示させる（Fizz, Buzz）](https://play.vuejs.org/#eNp9kkFrE0EUx7/KMCelISFUL3EbtFJBDyrqcS5xM4nb7s4uuzM1dFnY2UgNNUEQYhE8qEgpFKvgTdR+mMfGfgzf7JiYQts9zfzf7739z3svpbeiqL6tOG1RJ3FjL5Ik4VJFbSa8IApjSVIS816NuGEQKcm7JCO9OAwIo5jF6A0m3FAkEuNKSLJm4CvNqyg7DVsPK+FF8iDyO5LjjRDHlCf4QXEExQEMv8NwBMP3UJyYc/FmtvcT9DvQh7PpN9DjZvlpH/QI9G+j5oVVV0Efl/mkuhwjC3oC+ivk4zvezg7kE8i1Ba9fBK6rs2DzQtKUnNNGfgF6d/b2ZfllvxyhtfHpx8M/n3+AnkIxhuIVFGh2F/TR6cmvcu8DaGQOQL8GjeepSc+LqhEN2wnnqZIyFOSm63vu1hqjVTdXVhhtL7fIaVhu3kT02SJp+q/3WbYoF7WtoZZVnMZS+5mgNSoTnFrP69c3k1Dg7FOTZn4bRJ7P4weR9HCqjGJ5OylGO74fPr9XaTJWvDbX3Wfc3TpH30wGRmP0YcwTHm/jsixishP3ubThjcf3+QDPi2AQdpWP9CXBRzwJfWU8WmxdiS7aXuIqt3erDfZE/0myMZBcJPNHGaOGzCq+WuXblzz9v93V+rUqj4mMZn8B7+JogQ==)

**Comment by knokmki612** [comment]
> 15の倍数は3の倍数でもあり5の倍数でもあるので、その処理を考えるところでプログラム初心者には少しハードル高そうですね。FizzBuzzと表示させるには工夫が必要かも。

3の倍数か5の倍数の片方のパターンに取り組めればまずはいいんじゃないですかね。設問に書いたこと全部やる必要は必ずしもないので
