### ISSUE TITLE
靴のギャラリーの解答例を改善する

### ISSUE THREAD

**Issue by Hidetaro7** [tuqulore/vue-3-practices#684]
- [x] ~~Fetch API を使わず、import文による静的JSONの読み込みを行う~~ onMounted フックを使わない例を作成する
  - onMounted が急に出てくる
  - Fetch API については Nuxt で取り扱う際にトピックが重複する
  - [トップレベルのawait](https://ja.vuejs.org/api/sfc-script-setup#top-level-await)を使うにはSuspenseとの組み合わせを考慮するなど、前提条件が複雑なため
- [x] スコープ付きスロットによるデザインパターンの参考例を紹介する
- [x] README の Stackblitz による完成サンプルリンクを変更
- [x] スライドの靴のギャラリーのページにスコープ付きスロットのサンプルリンクを貼る
- [x] ダウンロード用ソースコードの修正

せっかくスコープ付きスロットの説明が前述されているので、ここでは一つの解答例に限らず様々な手段を紹介するという意味でも応用例として紹介するのもより良い気がする。サンプル作成済み。

靴のギャラリー - スコープ付きスロットを使った見た目とロジックの分離
https://stackblitz.com/edit/tuqulore-vue-3-practices-de8aybet?file=src%2FApp.vue

**Comment by knokmki612** [comment]
> - onMounted が急に出てくる

fetch と Vue Router を扱うサンプルでは、ある時点からmountedイベントフックはやめて、setup時のタイミングで実行されるようにしました。
参考https://ja.vuejs.org/guide/essentials/lifecycle.html#lifecycle-diagram

ご参考まで:

https://github.com/tuqulore/vue-3-practices/blob/3253fd8c602a118ea57db3ade723b509433ed93e/handson-fetch-router-finish/src/components/PostDetail.vue#L13-L21

**Comment by Hidetaro7** [comment]
チェック済みの反映をPRに出しました。確認をお願いします。 @knokmki612
