### ISSUE TITLE
教材に関する問い合わせのリンクを置く

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/vue-3-practices#82]
関連: https://github.com/tuqulore/branding/issues/27

Googleアンケートフォームなどを使って問い合わせの動線を用意する

**Comment by Hidetaro7** [comment]
## 対象
この教材で教えてもらいたい
企業内研修・学生教育

## フォーム項目
- どのくらいの期間で研修をお考えですか？
 - 3ヶ月間程度で毎週
- 受講人数は何人くらいでお考えでしょうか？
 - n人程度
- オンライン受講は可能ですか？
 - はい
 - いいえ
- 御社・御校名
- ご担当者様名
- ご担当者様メールアドレス
- お問い合わせ内容・ご相談補足などあればお聞かせください
 - 自由記入

**Comment by knokmki612** [comment]
#103 で用意した
